version: '3.8'

services:
  frontend:
    build: ./src/frontend
    ports:
      - "3000:3000"
    networks:
      - ecommerce-net

  backend:
    build: ./src/backend
    ports:
      - "5000:5000"
    networks:
      - ecommerce-net
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - ecommerce-net
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  ecommerce-net:

volumes:
  db-data:
